import React, {useState} from 'react';
import { Tabs, Tab, Carousel, Fade } from 'react-bootstrap';
import './Portfolio.css';
import DFA1 from "../../shared/images/DFA1.jpg";
import ConvexHull from "../../shared/images/ConvexHull.png";

function getTabData(data){
  var tabList = [];
  var tabElement = null;
  var index = 0;
  var paragraphElements = [];
  for (const [year, infoArray] of Object.entries(data)){
    // eslint-disable-next-line
    infoArray.forEach(info => {
      // eslint-disable-next-line
      paragraphElements.push(<p key = {index}>{info}</p>)
      index += 1;
    });
    tabElement = <Tab key = {index} eventKey={year} title={year}>
      {paragraphElements}
    </Tab>
    index += 1;
    tabList.push(tabElement);
    paragraphElements = [];
  }

  return tabList;
}

const PortfolioCarousel = () => {
  const [index, setIndex] = useState(0);
  const handleSelect = (selectedIndex, e) => {
    setIndex(selectedIndex);
  };

  return <Carousel className="PortfolioCarousel" activeIndex = {index} onSelect = {handleSelect}>
      <Carousel.Item className = "carouselItem">
        <img className = "d-block w-100 img-fluid"
          src={DFA1}
          alt="First Slide"
        ></img>
        <Carousel.Caption>
          <h3>Finite State Machine for the Ordered Mixing of Two Strings</h3>
          <p>My best friend Tom and I spent eight hours in an academic building attempting to solve this challenging Theory of Computation homework exercise.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item className = "carouselItem">
        <img className = "d-block w-100 img-fluid"
          src={ConvexHull}
          alt="Second Slide"
        ></img>
        <Carousel.Caption>
          <h3>Convex Hull Visualization</h3>
          <p>A model of a 3D convex hull, generated by performing a geometric lift using a convex function. Its shadow is a delaunay triangulation.</p>
        </Carousel.Caption>
      </Carousel.Item>
    </Carousel>
}



class Portfolio extends React.Component{
  render(){
    return <div className="Portfolio">
      <div className = "PortfolioInfo">
        <h4>Portfolio</h4>
        <p>My computer science skillset comprises of web development, object-oriented design, database creation and organization, and algorithm design.</p>
        <p>Below are descriptions of several projects that I have completed over the past three years:</p>
        <hr/>
      </div>
      <Tabs defaultActiveKey="2019" transition={Fade} id="uncontrolled-tab-example" className="mb-3">
        {getTabData(this.props.data)}
      </Tabs>
      {<PortfolioCarousel/>}
    </div>
  }
}

export default Portfolio;